services:
  - type: web
    name: orbit-backend
    env: node
    buildCommand: npm --prefix backend install && npm run --prefix backend db:push
    startCommand: npm --prefix backend run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
    autoDeploy: true
    healthCheckPath: /health
